# based on cycjimmy/semantic-release-action
name: 'WTW Omni Repo - Versioning'
description: 'Github Action for determining version bumps for .net core projects'
author: 'aabenoja'
branding:
  icon: 'package'
  color: 'orange'
inputs:
  shared_project:
    required: false
    description: 'The name of a project that should result in all projects being updated. All projects are versioned independently by default.'
  exclude_shared_project:
    required: false
    description: 'Selectively exclude the specified shared project from the version_list output. The shared project is included by default.'
outputs:
  version_list:
    description: 'A JSON array of the projects that require a version bump'
runs:
  using: 'node12'
  main: 'index.js'
